#!/bin/bash

flatpak install -y flathub com.google.Chrome com.mattjakeman.ExtensionManager org.telegram.desktop org.onlyoffice.desktopeditors org.kde.krita org.inkscape.Inkscape org.kde.kdenlive com.obsproject.Studio com.discordapp.Discord com.github.libresprite.LibreSprite org.qbittorrent.qBittorrent com.ultimaker.cura us.zoom.Zoom io.mpv.Mpv org.gnome.Boxes org.gnome.design.Contrast com.github.tenderowl.frog com.github.tchx84.Flatseal com.github.neithern.g4music com.valvesoftware.Steam com.heroicgameslauncher.hgl

